#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSample.Resource", IsApplication=true)]

namespace AndroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.font = global::AndroidSample.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::AndroidSample.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::AndroidSample.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::AndroidSample.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::AndroidSample.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::AndroidSample.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::AndroidSample.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::AndroidSample.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::AndroidSample.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Boolean.abc_action_bar_embed_tabs = global::AndroidSample.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::AndroidSample.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::AndroidSample.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::AndroidSample.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::AndroidSample.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::AndroidSample.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::AndroidSample.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::AndroidSample.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::AndroidSample.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::AndroidSample.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::AndroidSample.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::AndroidSample.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::AndroidSample.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::AndroidSample.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::AndroidSample.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::AndroidSample.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::AndroidSample.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::AndroidSample.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::AndroidSample.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::AndroidSample.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::AndroidSample.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::AndroidSample.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::AndroidSample.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::AndroidSample.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::AndroidSample.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::AndroidSample.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::AndroidSample.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::AndroidSample.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::AndroidSample.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::AndroidSample.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::AndroidSample.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::AndroidSample.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::AndroidSample.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::AndroidSample.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::AndroidSample.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::AndroidSample.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::AndroidSample.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::AndroidSample.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::AndroidSample.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::AndroidSample.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::AndroidSample.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::AndroidSample.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.async = global::AndroidSample.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::AndroidSample.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::AndroidSample.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::AndroidSample.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::AndroidSample.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::AndroidSample.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::AndroidSample.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::AndroidSample.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::AndroidSample.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::AndroidSample.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::AndroidSample.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::AndroidSample.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::AndroidSample.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::AndroidSample.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::AndroidSample.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::AndroidSample.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::AndroidSample.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.text = global::AndroidSample.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::AndroidSample.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::AndroidSample.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::AndroidSample.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::AndroidSample.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::AndroidSample.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::AndroidSample.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::AndroidSample.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::AndroidSample.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::AndroidSample.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::AndroidSample.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::AndroidSample.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::AndroidSample.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::AndroidSample.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::AndroidSample.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::AndroidSample.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::AndroidSample.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::AndroidSample.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::AndroidSample.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::AndroidSample.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::AndroidSample.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::AndroidSample.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::AndroidSample.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::AndroidSample.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::AndroidSample.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::AndroidSample.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::AndroidSample.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::AndroidSample.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::AndroidSample.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abc_action_bar_embed_tabs = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090006
			public const int colorAccent = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int colorPrimary = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int colorPrimaryDark = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int ic_launcher_background = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int notification_action_color_filter = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int notification_icon_bg_color = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ripple_material_light = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int secondary_text_default_material_light = 2131296259;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080004
			public const int compat_button_inset_horizontal_material = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int compat_button_inset_vertical_material = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int compat_button_padding_horizontal_material = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int compat_button_padding_vertical_material = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int compat_control_corner_material = 2131230728;
			
			// aapt resource value: 0x7f080014
			public const int fab_margin = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int notification_action_icon_size = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int notification_action_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int notification_big_circle_margin = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int notification_content_margin_start = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int notification_large_icon_height = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int notification_large_icon_width = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int notification_main_column_padding_top = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int notification_media_narrow_margin = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int notification_right_icon_size = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int notification_right_side_padding_top = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int notification_small_icon_background_padding = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int notification_small_icon_size_as_large = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int notification_subtext_size = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int notification_top_pad = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int notification_top_pad_large_text = 2131230739;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000b
			public const int action_container = 2131427339;
			
			// aapt resource value: 0x7f0b0017
			public const int action_divider = 2131427351;
			
			// aapt resource value: 0x7f0b000c
			public const int action_image = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int action_text = 2131427341;
			
			// aapt resource value: 0x7f0b0018
			public const int actions = 2131427352;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b0016
			public const int chronometer = 2131427350;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b000f
			public const int icon = 2131427343;
			
			// aapt resource value: 0x7f0b0019
			public const int icon_group = 2131427353;
			
			// aapt resource value: 0x7f0b0012
			public const int info = 2131427346;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b0014
			public const int notification_background = 2131427348;
			
			// aapt resource value: 0x7f0b0010
			public const int notification_main_column = 2131427344;
			
			// aapt resource value: 0x7f0b000e
			public const int notification_main_column_container = 2131427342;
			
			// aapt resource value: 0x7f0b0013
			public const int right_icon = 2131427347;
			
			// aapt resource value: 0x7f0b0011
			public const int right_side = 2131427345;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b0015
			public const int time = 2131427349;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0000
			public const int status_bar_notification_info_maxnum = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int notification_action = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action_tombstone = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_template_custom_big = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_icon_group = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_part_chronometer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_time = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_Compat_NotificationActionContainer = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int Widget_Compat_NotificationActionText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int xamarin_essentials_fileprovider_file_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
